name: Create the PR to `draft` branch for release blog post
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of OpenLiberty to generate blog for, e.g. 22.0.0.9, 22.0.0.9-beta'
        required: true
        type: string
      publish-date:
        description: 'Date of publish of the blog, format: YYYY-MM-DD'
        required: true
        default: '2050-01-01'
        type: string
      author-name:
        description: 'Name of the author, put the name in quotes if the name contains space'
        required: true
        # default: ${{ github.actor }}
        type: string
      github-username:
        description: 'GitHub username of the author'
        required: true
        # default: ${{ github.actor }}
        type: string
      slack-notification:
        description: 'Send Slack notification'
        required: true
        default: 'release channel'
        type: choice
        options:
        - 'release channel'
        - 'test channel'
        - 'off'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  create_blog_and_draft_pr:
    name: Automate release and beta blog PR creation for `draft` branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Create blog
        run: |
          python3 .github/workflows/gen_blog.py ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }}

      - name: Generate draft and staging URLs
        id: gen-url
        run: |
          echo "::set-output name=draft-url::https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/$(echo ${{ inputs.publish-date }} | tr - /)/${{ inputs.version }}.html"
          echo "::set-output name=staging-url::https://staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/$(echo ${{ inputs.publish-date }} | tr - /)/${{ inputs.version }}.html"

      - name: Create PR to draft branch
        id: create-pr-draft
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ inputs.version }}
          branch: ${{ inputs.version }}-post
          base: prod
          title: ${{ inputs.version }} draft
          assignees: ${{ github.actor }}
          body: "After this PR is merged, preview at draft site: ${{ steps.gen-url.outputs.draft-url }}"

      - name: Send Slack alert
        run: |
          python3 .github/workflows/slack_alert.py \
          ${{ inputs.version }} ${{ inputs.publish-date }} ${{ inputs.author-name }} ${{ inputs.github-username }}  ${{ inputs.slack-notification }} \
          ${{ secrets.SLACK_HOOK }} ${{ secrets.SLACK_HOOK_TEST }} \
          ${{ steps.create-pr-draft.outputs.pull-request-number }} draft ${{ steps.gen-url.outputs.draft-url }}
